name: 'Test & Lint'

on:
    pull_request:
    push:
        branches:
            - dev
            - main

jobs:
    install:
        name: 'Install/Test/Lint'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup React Build Node.js
              uses: actions/setup-node@v3
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
                  NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}
              with:
                  cache: 'yarn'
                  node-version: '20.18.9'
                  registry-url: 'https://npm.pkg.github.com'
            - name: Install dependencies
              run: yarn install --frozen-lockfile
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
                  NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}

            - name: Lint
              run: yarn lint

            - name: Test & publish code coverage
              run: yarn test:ci

            - uses: DTSL/actions/js/quality-checks@v1
              name: Quality Checks
              with:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                  SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
                  sources: src/
